### ISSUE TITLE

"create-event" command shows Discord API returned error messages



### ISSUE THREAD

**Issue by slingexutils** [slingexbot/issues#20]
When you specify a different channel than the type provided, it returns this error that looks like it was directly returned from the Discord API. This could be confusing for some people imo

![image attachment](https://media.discordapp.net/attachments/928004229753344021/928055551861084230/unknown.png)

**Comment by slingexutils** [comment]
Opened by `OrwoTech#5939` (`846498322365677588`)

**Comment by milanmdev** [comment]
Can reproduce.
**Command:**
`/create-event name: test description: test type: STAGE_INSTANCE channel: #Voice Channel start_time: tomorrow at 5pm`

![image](https://user-images.githubusercontent.com/29466935/148134901-97603bb3-274b-43ed-9951-7bbdef19233d.png)

**Comment by JoshuaMikes107** [comment]
I can also reproduce this!
**Command:**
`/create-event name: test description: test type: STAGE_INSTANCE channel: #General start_time: tomorrow at 19:21`

![image](https://user-images.githubusercontent.com/79803381/148135074-853a0411-6760-4377-b5d2-b3bf0bb3ff70.png)

**Comment by milanmdev** [comment]
Fixed in release `v2.3.8` 🎉
