### ISSUE TITLE

Quote webhooks don't allow message links from other guilds



### ISSUE THREAD

**Issue by slingexutils** [slingexbot/issues#25]
When a user sends a message link from another guild (in which the bot is in & the author has access to the message), the link will not get converted into a quote webhook message.

[REPRODUCTION STEPS]
1) Send a message link to a message in another guild for a message that you have access to read

![image attachment](https://media.discordapp.net/attachments/930640596048162836/930641313504841810/IMG_3965.png)

**Comment by slingexutils** [comment]
Opened by `mdev01#0001` (`423203831971708958`)

**Comment by milanmdev** [comment]
Patched in `v2.3.10`
