### ISSUE TITLE

Slash commands can be used in verification channels



### ISSUE THREAD

**Issue by slingexutils** [slingexbot/issues#26]
Slash commands can be used in verification channels whereas messages are not. Slash commands (other than /captcha-verify should not be allowed.

[REPRODUCTION STEPS]
1) Join a server with the captcha system enabled
2) Run a slash command in the channel

![image attachment](https://media.discordapp.net/attachments/930659754043400252/930660999219003442/unknown.png)

**Comment by slingexutils** [comment]
Opened by `JoshuaMikes107#2985` (`815385483583815730`)

**Comment by milanmdev** [comment]
Discord will soon be adding Slash command permissions to channels (e.g. you can configure what commands will show up in a channel).

I will be adding the `wontfix` tag to this.
