### ISSUE TITLE

User & Report commands time out



### ISSUE THREAD

**Issue by slingexutils** [slingexbot/issues#27]
The `user` and `report` commands both time out. This is due to the Dangerous Discord User Database being shut down and the api being taken down. The fix will involve switching to https://discord.drivet.xyz for the reporting & checking of users.

[REPRODUCTION STEPS]
Run the `user` or `report` command and wait for it to time out (or just watch it load).

![image attachment](https://media.discordapp.net/attachments/937847957309493348/937848475343806484/unknown.png)

**Comment by slingexutils** [comment]
Opened by `mdev01#0001` (`423203831971708958`)

**Comment by milanmdev** [comment]
Patched in `v2.3.11`
